server:
  port: 8082

spring:
  application:
    name: cities-service
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
