server:
  port: 8083

spring:
  application:
    name: hotels-service
  cloud:
    discovery:
      enabled: true
    # Configuración de Eureka Client
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka
